### ISSUE TITLE
fix(fw*) : rename libraries and functions.

### ISSUE THREAD

**Issue by luisjomen2a** [IRCAD-IHU/sight#1]
# Description

- Some libraries and functions still have the old prefix "fw" 

Attached you will find a list of 60823 appearances of said prefix.

I really like this new toolkit name, so it would be great if you could actually rename everything. :)

# Proposition

- Use CLTR + F to change prefix from "fw" to "f4".

[Uploading fwPrefix.txt…]()

**Comment by schweitzer** [comment]
This as been fixed in the latest dev branch, enjoy ;)

**Comment by luisjomen2a** [comment]
![giphy](https://user-images.githubusercontent.com/2832538/111520081-0a067800-8758-11eb-943d-acf9b4816ef9.gif)

**Comment by fbridault** [comment]
You're welcome ;-)

**Comment by gKevin** [comment]
![feels-good](https://user-images.githubusercontent.com/2741784/111605302-16c5b300-87ce-11eb-9c71-a59a594916fc.jpg)

Neat, well done!

**Comment by fbridault** [comment]
We also reworked the build system, killed the famous Properties.cmake, ADDITIONNAL_REPOSITORIES and other PROJECTS_TO_BUILD !
