### ISSUE TITLE
how do i use this application?

### ISSUE THREAD

**Issue by Zumbalamambo** [IRCAD-IHU/sight#2]

**Comment by schweitzer** [comment]
Hello,

Sorry for the late reply,

What do you mean by "application" ? Sight is a toolkit.

If by "application" you mean the VRRender application, please visit our [documentation page](https://sight.pages.ircad.fr/sight-doc/Installation/index.html) to know how to compile **VRRender** from source. Unfortunately we don't provide binaries yet.

Let us know if you need more details.

**Comment by Zumbalamambo** [comment]
May I know how do you use openvslam to localize the coordinates in the model space or world space since the map is a sparse pointcloud?

**Comment by schweitzer** [comment]
Hello,
that's a very specific question.

First of all our integration of openvslam is a very preliminary work, so it is far from being complete.

As far as I know we didn't start to work on the registration between models and openvslam map for now.

If you run `ExOpenvslam` you can only track the camera position, save/load map. but you will not be able to register any 3d object on openvslam map. This will probably be added in the futur, but I can't tell you when.

![ExOpenvslam](https://user-images.githubusercontent.com/1426321/84037811-63f33980-a99f-11ea-88fc-a29a646457a7.png)

**Comment by schweitzer** [comment]
No update on this, I close the issue.
